# Generated by Django 4.2.29 on 2026-04-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
