# Generated by Django 4.2.29 on 2026-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
