# Generated by Django 4.2.29 on 2026-04-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
